### ISSUE TITLE
Add Readme content to table format

### ISSUE THREAD

**Issue by vidhyav656** [vidhyav656/The-Most-Useful-Websites-and-Web-Apps#6]
For example

| Link | Description |
|------|--------------|
| [archive.is](http://archive.is) | take a snapshot of any web page and it will be exist forever even if the original page is gone. |
| [autodraw.com](http://autodraw.com) | create freehand doodles and watch them magically transform into beautiful drawings powered by maching learning. | 

To make the whole list in table format

**Comment by roccojiang** [comment]
@vidhyav656 I'd be willing to help out with this

**Comment by vidhyav656** [comment]
@rj14ng Sure. Please go ahead

**Comment by vidhyav656** [comment]
Thank you so much @rj14ng.
